"""Ajout du language dans le model 'Post'

Revision ID: 54902df3f25d
Revises: 30e2c790e8e3
Create Date: 2023-01-04 02:36:19.156652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54902df3f25d'
down_revision = '30e2c790e8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
