"""Ajout de businessMontreal

Revision ID: 8c77dbf1b223
Revises: 87135d9d0b33
Create Date: 2023-02-05 19:01:06.253672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c77dbf1b223'
down_revision = '87135d9d0b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_montreal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('statut', sa.String(length=128), nullable=True),
    sa.Column('date_statut', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_montreal_address'), 'business_montreal', ['address'], unique=False)
    op.create_index(op.f('ix_business_montreal_city'), 'business_montreal', ['city'], unique=False)
    op.create_index(op.f('ix_business_montreal_date_statut'), 'business_montreal', ['date_statut'], unique=False)
    op.create_index(op.f('ix_business_montreal_name'), 'business_montreal', ['name'], unique=False)
    op.create_index(op.f('ix_business_montreal_state'), 'business_montreal', ['state'], unique=False)
    op.create_index(op.f('ix_business_montreal_statut'), 'business_montreal', ['statut'], unique=False)
    op.create_index(op.f('ix_business_montreal_type'), 'business_montreal', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_montreal_type'), table_name='business_montreal')
    op.drop_index(op.f('ix_business_montreal_statut'), table_name='business_montreal')
    op.drop_index(op.f('ix_business_montreal_state'), table_name='business_montreal')
    op.drop_index(op.f('ix_business_montreal_name'), table_name='business_montreal')
    op.drop_index(op.f('ix_business_montreal_date_statut'), table_name='business_montreal')
    op.drop_index(op.f('ix_business_montreal_city'), table_name='business_montreal')
    op.drop_index(op.f('ix_business_montreal_address'), table_name='business_montreal')
    op.drop_table('business_montreal')
    # ### end Alembic commands ###
