"""Ajout attributs pour le modele User

Revision ID: 99efb52566e6
Revises: a173f4ba51cf
Create Date: 2022-11-11 22:25:18.355355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99efb52566e6'
down_revision = 'a173f4ba51cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
