"""Maj table BusinessMontreal

Revision ID: f56181971abe
Revises: 8c77dbf1b223
Create Date: 2024-01-12 20:43:32.149794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56181971abe'
down_revision = '8c77dbf1b223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_montreal', sa.Column('date_last_update', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_business_montreal_date_last_update'), 'business_montreal', ['date_last_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_montreal_date_last_update'), table_name='business_montreal')
    op.drop_column('business_montreal', 'date_last_update')
    # ### end Alembic commands ###
